application: academic-research-724 
version: 1
runtime: php
api_version: 1
threadsafe: yes


handlers:
- url: /test/imageTest.php
  script: /test/imageTest.php
  
- url: /test/soundTest.php
  script: /test/soundTest.php