application: academic-research-724 
version: 1
runtime: php
api_version: 1
threadsafe: yes


handlers:
- url: /test
  script: test
  
- url: /admin
  script: admin
  
  # Serve php scripts.
- url: /(.+\.php)
  script: \1
  
- url: .*
  script: index.html