application: academic-research-724 
version: 1
runtime: php
api_version: 1
threadsafe: yes


handlers:
  # Serve php scripts.
#- url: /test/imageTest.php
#  script: /test/imageTest.php
  
- url: /(.+)/(.+)\.php$
  script: \1\2

- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php