application: academic-research-724 
version: 1
runtime: php
api_version: 1
threadsafe: yes


handlers:
  # Serve php scripts.
- url: /test/imageTest.php
  script: /test/imageTest.php
  
- url: /test/soundTest.php
  script: /test/soundTest.php
  
- url: /admin/admin.php
  script: /admin/admin.php
  
- url: /admin/createImageTest.php
  script: /admin/createImageTest.php
  
- url: /admin/createSoundTest.php
  script: /admin/createSoundTest.php
  
- url: /admin/viewImageTests.php
  script: /admin/viewImageTests.php
  
- url: /admin/viewImageResults.php
  script: /admin/viewImageResults.php
  
- url: /admin/viewSoundTests.php
  script: /admin/viewSoundTests.php
  
- url: /admin/viewSoundResults.php
  script: /admin/viewSoundResults.php
  
- url: /functions/functions.php
  script: /functions/functions.php
  
- url: /results/saveImageResponses.php
  script: /results/saveImageResponses.php
  
- url: /results/saveSoundResponses.php
  script: /results/saveSoundResponses.php
  
- url: /config/footer.php
  script: /config/footer.php
  
- url: /config/global.php
  script: /config/global.php
  
- url: /config/header.php
  script: /config/header.php
  
- url: /config/modules.php
  script: /config/modules.php
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /images
  static_dir: images
  
- url: /fonts
  static_dir: fonts
  
- url: /results/image_responses.json
  static_files: /results/image_responses.json
  
- url: /results/sound_responses.json
  static_files: /results/sound_responses.json
  
- url: /test/image_tests.json
  static_files: test/image_tests.json
  
- url: /test/sound_tests.json
  static_files: test/sound_tests.json
  
- url: /test/tone.wav
  static_files: test/tone.wav
  
- url: /(.+)/(.+)\.php$
  script: \1\2

- url: /(.+\.php)$
  script: \1
  
- url: /.*
  script: index.php